TOKEN = "hvH25Sxkr4Ys4FiSNWQiwt2xZ0xct9mYRLsBw5dq9BoRfEwVjMuqYBXizt5Nl-hsjRLcu1Ge3aS1-Os6CYSAcf"

[google_service_account]
type = "service_account"
project_id = "our-metric-440014-f5"
private_key_id = "3e6296bfc0aad7bff08e8a963a53ec93d0c59ea0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmU0YrppunPsoI
NKVb/QKWdmPpQs81182NVYIKD0VDLeaDHhFbRtibKton13rW2dH0N8WgogitwX9A
KkXm6XusYsx1aA8WCc1pVU26wt9ZZHpGYGJDXOMAfhCgk2Nk5ZsHR/iTAaB7WWcu
bYSddKDIK/zOjQLrL4awVpv2s+2/eIJxuvqIG74Rfm0E2LriQnhNbY5OHsMP0Jwu
cCys3cgTNBktJGhGhQvVfZ7a3l7KCM36pDibTuTjUlkqjXHDgIssE7YFlVNWTV4q
S7s/F+WVKm73zHcbJuGk+2bLrtWf0646prAnmVNxZXaFF7AR466shIQzJqnK6QLF
jiOtn1eBAgMBAAECggEADO0872iQAWQWZKPe1DLqUBJceoUYQKmIjrr+E9US/4Ei
QL+F/s+XRxwB/4W2RNuB/1aUVAMz5Hk88Bo4+5Ta6U92b4uKXJ6fadfY5jJ+FF8E
R9L24CBofiHOHgTGfVGBBoRX8+j09ZFBvTCC1Y/6bQRKLi10dB3p/GuGzJo4WKCf
ahE/XwT3P4zFPrhrGg18FnGXkM0TGww4+OsvECS8Ck1M4U5nousL6wk9LoIOTbCO
TxYe+vam0/LdAPe5V1eH7LpnQT+MpMGhmByYM9w2pg2YA8RcXx2B/XMbiG50qt/T
VeSxkUOnYWh6UjC8N3BqWHIlnbULa9ity/1CeMg4CQKBgQDfRJ2Agww8zvhPLhrk
McK9VM+m/SFnF/VJb2/2pSNsks6ZT/GiuUcnYtkmQk7/sBXcbQ+5LUn1uDiZ9SSt
ZdbvDohRNGEq/mXO4zN0I4yfnLFJt16WGRWlwwpgiF/TcmSqwemm9cvpkGlmE0o5
unOJAwKMOQo35wlxNC4FwRP0rQKBgQC+tZAy0Bg2K6EkRch6QzQ1G1zXY6d+l12s
AEF5iclGhB+t0lPrzv96PnbsqMg5pS04YzbcGu7BQCzSsWO5u4ee3d+hcszHJmjc
g+zcwmlyo3IuWxLGha33ANJKkII+Zcz9TcO49NNjJBBbmaGDs7WEVYX8gfs3av4e
nU800L20pQKBgQCZdPrgmrItlYA8RA89qyoTohh7yV5NEr2INOz61PRtKtaPr9AA
rWJHovxn/Il52picAeYdvBAqsO1OfJ0yBV5ev1lYnyzuNR7avXTfLZP5HOUKKtv7
RNCJN26JfRKILgcdCt1C4Yy/Q3/+JeINnabNlGEK6iWo2Ma3pUrAr728nQKBgDZM
s/YD0iD6YzNUuzQ0llTYqaKaOUKODpm+qOXWGXz+eZagYEyv74X66xmPJRNkuG9p
sGETOg/EGf8TivWDM6ZEPjxV14CMqya+WV6x7Bw79XLFc58ayOGfVkDszGi/y5ID
5kpvSxDbX9z07Uv2iyRWxYOT7tdkm15UJA1BsgIRAoGAFvZSrSPlQT3Hb/lECmXw
TFGB4HdaYBISYDu2DwAS9hF7fwJLPY5IRdclNt3Nuh/RRCLkVVnNGcjHW4ssyUdP
K5+vFdUcM06aQeWMANqpsxyDcAsa0TT3jtlXRcN2JVBUHPH12y5MM4wFucHjk84x
aWFqyzMz4RCiUTTOkuV+LWI=
-----END PRIVATE KEY-----"""
client_email = "cuentadeserviciogooglesheets@our-metric-440014-f5.iam.gserviceaccount.com"
client_id = "115085866289702892716"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/cuentadeserviciogooglesheets@our-metric-440014-f5.iam.gserviceaccount.com"
